# Generated by Django 3.2.2 on 2021-05-11 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_lesson_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='price',
            name='description',
        ),
        migrations.RemoveField(
            model_name='price',
            name='description_short',
        ),
        migrations.RemoveField(
            model_name='price',
            name='teacher_pk',
        ),
        migrations.AddField(
            model_name='price',
            name='price',
            field=models.IntegerField(default=1000),
        ),
        migrations.CreateModel(
            name='PriceDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_pk', to='accounts.discipline')),
                ('price_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_pk', to='accounts.price')),
                ('teacher_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_pk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
